# Generated by Django 4.2.3 on 2023-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_de_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('id_de_usuario', models.IntegerField()),
                ('nombre_corto_problema', models.CharField(max_length=150, verbose_name='Nombre corto del problema')),
                ('descripcion_problema', models.CharField(max_length=1300, verbose_name='Descripción del problema')),
                ('status', models.CharField(choices=[('enviado', 'Enviado/Pendiente de revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_revision', 'En proceso de revisión')], default='enviado', max_length=20, verbose_name='Status')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación de coordenadas o descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_de_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('confirma_tu_contrasena', models.CharField(max_length=128, verbose_name='Confirma tu contraseña')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tipo_usuario', models.CharField(choices=[('Ciudadano', 'Ciudadano'), ('Servidor', 'Servidor')], default='Ciudadano', max_length=20, verbose_name='Tipo de usuario')),
            ],
        ),
    ]
